create database amazon;
use amazon;
select * from amazon;

--                                                   Total Sales Overview
-- --------------------------------------------------------------------------------------------------------------------------------------

-- 1. Find the total revenue generated by the company
select sum(total_revenue ) as total_revenue_generated from amazon;

-- 2. Calculate total profit earned
select sum(profit) total_profit from amazon;

-- 3. Find total quantity sold across all products.
select sum(quantity_sold) total_quantity from amazon;

-- 4. Count total number of orders placed.
select count(order_id) total_orders from amazon;


--                                                       Category Performance
-- --------------------------------------------------------------------------------------------------------------------------------------

-- 5. Find total revenue generated by each product category
select product_category,sum(total_revenue) revenue from amazon group by product_category;

-- 6. Which product category generated the highest profit?
select product_category,revenue from
(
select product_category , sum(profit) revenue ,
rank() over(order by sum(profit) desc ) rnk
from amazon group by product_category 
) t
where rnk=1;

-- 7. Find the average rating per category.
select product_category , round(avg(rating),2) average_rating from amazon group by product_category;

-- 8. Find top 3 categories by total quantity sold
select product_category , sum(quantity_sold) total_quantity_sold from amazon 
group by product_category order by total_quantity_sold desc limit 3;

-- 9. Which category has the highest average discount?
select product_category , round(avg(discounted_price),2) average_discount from amazon 
group by product_category order by average_discount desc limit 1;

--                                                    Regional Analysis
-- ---------------------------------------------------------------------------------------------------------------------------------

-- 10. Find total revenue generated from each customer region.
select * from amazon;
select customer_region , sum(total_revenue) total_revenue from amazon
group by customer_region ;

-- 11. Which region generated the highest profit?
select customer_region , sum(profit) total_profit from amazon
group by customer_region order by total_profit desc limit 1;

-- 12. Find average rating given by customers in each region.
select customer_region , round(avg(rating),2) average_rating from amazon group by customer_region;

-- 13. Count number of orders per region.
select customer_region ,count(*) number_of_orer from amazon group by customer_region;

-- 14. Which region has highest average order value?
select customer_region , avg(total_revenue) average_order_value from amazon
group by customer_region order by average_order_value desc;


--                                                   Payment Insights
-- --------------------------------------------------------------------------------------------------------------------------------------

-- 15. Find total revenue by each payment method.
select payment_method , sum(total_revenue) total_revenue from amazon group by payment_method;


-- 16. Which payment method is most used?
select payment_method , count(*) count_of_method from amazon
group by payment_method 
having count(*) = (
select max(cnt) from
(
select count(*) cnt from amazon group by payment_method
) t
);

-- 17. Find average order value per payment method.
select payment_method , avg(total_value) order_value from 
(
select order_id,payment_method,sum(total_revenue) total_value from amazon group by order_id,payment_method
)  t 
group by payment_method;


-- 18. Which payment method generates highest profit?
select payment_method , total_profit from
(
select payment_method,sum(profit) total_profit ,
rank() over (order by sum(profit) desc) rnk 
from amazon
group by payment_method
) x
where rnk=1;
 
 
 --                                                  Date & Time Analysis
 -- ----------------------------------------------------------------------------------------------------------------------------------
-- 19. Extract year and month from order_date.
select year(order_date) as Year,month(order_date) months from amazon;
select date_format(order_date,'%Y-%m') date from amazon;

-- 20. Find total revenue generated in each year.
select year(order_date) year , sum(total_revenue) total_revenue from amazon 
group by year(order_date) order by total_revenue;
  
-- 21. Find month-wise sales report.
select date_format(order_date,'%Y-%m') as year_months ,sum(total_revenue) revenue  from amazon
group by year_months
order by year_months;

-- 22. Find the month with highest revenue.
select year_months,revenue from (
select date_format(order_date,'%Y-%m') year_months ,sum(total_revenue) revenue ,
rank() over(order by sum(total_revenue) desc ) rnk
from amazon group by year_months
) t
where rnk =1;

-- 23. Compare yearly growth in revenue.
select year,revenue,
lag(revenue) over (order by year ) yearly_growth,
(revenue - lag(revenue) over (order by year )) yearly_growth_Difference,
concat(round(((revenue - lag(revenue) over (order by year ))/(lag(revenue) over (order by year ))*100.0),2),'%') as growth_percentage
from 
(
select year(order_date) year,sum(total_revenue) revenue from amazon group by year(order_date)
) t ;

-- 24. Find total profit per year.
select year(order_date) year , sum(profit) total_profit from amazon group by year(order_date);

--                                                 Discount Analysis
-- --------------------------------------------------------------------------------------------------------------------------------------
-- 25. Find average discount percentage overall.
select round(avg(discounted_price),2) discount_percentage from amazon;

-- 26. Find revenue generated from orders having discount > 20%.
select round(sum(total_revenue),2) total_revenue,
round((sum(total_revenue)/(select sum(total_revenue) from amazon))*100,2) as percent_contribution
from amazon where discount_percent>20;

-- 27. Which category gives highest average discount?
select product_category , avg(discount_percent) avg_dict from amazon group by product_category order by avg_dict desc limit 1;

-- 28. Find profit impact of high discount products.

select discount_percent ,round(sum(total_revenue),2) total_revenue
from amazon 
group by discount_percent
having  discount_percent in (0,10,20,30) 
order by discount_percent;

-- 29. Find top 5 most discounted products.
select product_category,max(discount_percent) discount_percent from amazon
group by product_category
order by discount_percent desc limit 5;

--                                                   Customer Behavior
-- ---------------------------------------------------------------------------------------------------------------------------
-- 30. Find top 5 highest rated products.
select product_id,avg_rating from (
select product_id,avg(rating) avg_rating,
rank() over (order by avg(rating) desc) as rnk
from amazon group by product_id) as t
where rnk<=5
;

-- 31. Find products with rating below 3
select distinct product_id,rating from amazon where rating <3;

-- 32. Find correlation indicator: products with high review_count but low rating.
select distinct product_id,review_count,rating from amazon
where review_count > 100 and rating<3;

-- 33. Find average review_count per category / 34. Which category has highest customer engagement (review_count)?.
select product_category , avg(review_count) review_count from amazon
group by product_category order by review_count desc ;

--                                        Revenue & Profit Analysis
-- --------------------------------------------------------------------------------------------------------------------------------------
-- 35. Find top 10 orders by total revenue.

select order_id , total_revenue from amazon order by total_revenue desc limit 10;
 
 select order_id , total_revenue from (
 select order_id , sum(total_revenue) total_revenue , rank() over (order by sum(total_revenue) desc) as rnk
from amazon group by order_id) t
where rnk<=10;

-- 36. Find top 10 most profitable orders.
select order_id,profit from (
select order_id,sum(profit) profit , rank() over (order by sum(profit) desc ) as rnk
from amazon group by order_id ) t
where rnk<=10;

-- 37. Calculate profit margin for each order.
select 
	order_id , 
	sum(total_revenue) total_revenue,
    sum(profit) profit ,
	concat(round((sum(profit)/sum(total_revenue))*100,2),'%') profit_margin 
from amazon
group by order_id;

-- 38. Find products with profit margin less than 10%.
select 
	product_id , 
	sum(total_revenue) total_revenue,
    sum(profit) profit ,
	concat(round((sum(profit)/sum(total_revenue))*100,2),'%') profit_margin 
from amazon
group by product_id
having profit_margin<10;

-- 39. Which category has highest average profit margin?
select 
	product_category ,
	avg((profit/total_revenue)*100) profit_margin 
from amazon
group by product_category
order by profit_margin desc ;


--                          SECTION 3: Advanced Level (Window Functions & Subqueries)
-- -------------------------------------------------------------------------------------------------------------------------------

-- 40. Find second highest revenue order
-- -----------------------------------------
with  second_highest as (
select order_id,sum(total_revenue) revenue,
dense_rank() over(order by sum(total_revenue) desc) as rnk
from amazon
group by order_id
)
select order_id,revenue from second_highest 
where rnk = 2;

select order_id,revenue from 
	  (
      select order_id , sum(total_revenue) revenue from amazon group by order_id
      ) x
      where revenue = (
                 select max(revenue) from (
                          select sum(total_revenue) revenue from amazon group  by order_id) x
                          where revenue < (select max(revenue) from (select sum(total_revenue) revenue from amazon group by order_id) y)
				);

-- 41. Find third highest profit overall. 
-- ---------------------------------------------------

with third as (
select order_id,sum(profit) total_profit,
row_number() over (order by sum(profit) desc ) as rnk 
from amazon
group by order_id
) 
select order_id,total_profit from third where rnk =3 ;

-- 42. Find top 3 products per category (using RANK()).
-- ----------------------------------------------------------
with top as (
        select product_id,
               product_category,
               sum(total_revenue) revenue ,
		       rank() over (partition by product_category 
               order by sum(total_revenue) desc) as rnk
        from amazon 
        group by product_category,product_id
           )
select product_category,
	   product_id,
       revenue 
from top
where rnk<=3;

-- 43. Find cumulative revenue over time. 
-- ---------------------------------------------------------
select * from amazon;

select year(order_date) year ,month(order_date) month,
       sum(total_revenue)  monthly_revenue,
       sum(sum(total_revenue)) over (order by year(order_date) ,month(order_date)) cumulative
from amazon 
group by year(order_date) ,month(order_date);


select year,month,
       sum(monthly_revenue) over(order by year,month) as cum_sum
from (
select year(order_date) year , month(order_date) month,
       sum(total_revenue) monthly_revenue
from amazon
group by year(order_date),month(order_date)
order by year(order_date),month(order_date)
)t;


-- 44. Calculate running total of profit by year. 
-- -------------------------------------------------
select year(order_date) year ,
	   sum(profit) totla_profit,
       sum(sum(profit)) over (order by year(order_date)) running_total
from amazon
group by year(order_date);


-- 45. Rank regions based on revenue. 
-- ------------------------------------------------------
select customer_region,sum(total_revenue) revenue,
       rank() over (order by sum(total_revenue) desc ) rnk 
from amazon 
group by customer_region;

-- 46. Find percentage contribution of each category to total revenue.
-- -------------------------------------------------------------------------------
select product_category,
       concat(round((category_revenue/total_revenue)*100,2),"%") contribution_percentage
from (
select product_category,
       round(sum(total_revenue)) category_revenue,
       (select sum(total_revenue) from amazon) total_revenue
from amazon
group by product_category
) t;

-- 47. Find orders where revenue is above category average. 
-- -----------------------------------------------------------------
SELECT a.order_id,
       a.product_category,
       a.total_revenue
FROM amazon a
JOIN (
    SELECT product_category,
           AVG(total_revenue) AS avg_revenue
    FROM amazon
    GROUP BY product_category
) t
ON a.product_category = t.product_category
WHERE a.total_revenue > t.avg_revenue;

-- 48. Find customers region where revenue is above overall average. 
-- ---------------------------------------------------------------------------
SELECT customer_region,
       SUM(total_revenue) AS revenue
FROM amazon
GROUP BY customer_region
HAVING SUM(total_revenue) > (
    SELECT AVG(region_revenue)
    FROM (
        SELECT SUM(total_revenue) AS region_revenue
        FROM amazon
        GROUP BY customer_region
    ) t
);

--                              SECTION 4: REAL BUSINESS CASE STUDY QUESTIONS 
--    -------------------------------------------------------------------------------------------------------------------------
--                                  Case Study 1: CEO Revenue Strategy 
--                                 The CEO wants to improve profitability. 

-- 49. Identify which category gives high revenue but low profit margin. 
-- -------------------------------------------------------------------------------

select product_category ,
       sum(total_revenue) revenue,
       sum(profit) profit,
       round((sum(profit)/sum(total_revenue))*100,2) profit_margin
from amazon
group by product_category
order by revenue desc,profit_margin asc;

-- 50. Find whether higher discounts actually increase quantity sold. 
-- --------------------------------------------------------------------
select * from amazon;



